import 'package:flutter/material.dart';

const List<String> iconSounds = [
  "anklung",
  "boltJingle",
  "boneSnap",
  "cards",
  "catRattle",
  "chewing",
  "congaOpen",
  "cookie_sheet_2",
  "cookieSheet",
  "cookieTin",
  "cowbellLargeClosed",
  "cowbellLargeOpen",
  "cowbellSmallClosed",
  "cowbellSmallOpen",
  "cymbalHihatStick",
  "cymbalHihatFoot",
  "drumBass",
  "eggShaker",
  "handDrum",
  "maracasDbl",
  "music_boxTone1",
  "music_boxTone3",
  "pencil_tick_1",
  "pencilScrape",
  "pipe_thump2",
  "pipe_thump3",
  "pipeThump",
  "pvc",
  "rubber_toyShort1",
  "rubber_toyShort3",
  "rubber_toyShort5",
  "screw",
  "sprinkler",
  "stone1",
  "stone2",
  "stone3",
  "tabla_hiNa",
  "tabla_hiTuh",
  "tabla_hiTuut",
  "tabla_lo_geh_gliss",
  "timbale_HiCrosstick",
  "whistle_owl",
  "woodblock_pitched_LOWERsol",
  "woodblock_pitched_mi",
  "woodblock_pitched_sol",
  "woodblock_pitched_ti"
];

const Map<String, IconData> basicIcons = <String, IconData>{
  "accessibility": Icons.accessibility,
  "accessible": Icons.accessible,
  "accessible_forward": Icons.accessible_forward,
  "account_balance": Icons.account_balance,
  "account_balance_wallet": Icons.account_balance_wallet,
  "account_box": Icons.account_box,
  "account_circle": Icons.account_circle,
  "add_shopping_cart": Icons.add_shopping_cart,
  "alarm": Icons.alarm,
  "anchor": Icons.anchor,
  "android": Icons.android,
  "aspect_ratio": Icons.aspect_ratio,
  "assignment": Icons.assignment,
  "autorenew": Icons.autorenew,
  "backup": Icons.backup,
  "book": Icons.book,
  "bookmark": Icons.bookmark,
  "bug_report": Icons.bug_report,
  "build": Icons.build,
  "cached": Icons.cached,
  "code": Icons.code,
  "commute": Icons.commute,
  "dashboard": Icons.dashboard,
  "delete": Icons.delete,
  "donut_small": Icons.donut_small,
  "drag_indicator": Icons.drag_indicator,
  "eco": Icons.eco,
  "eject": Icons.eject,
  "euro_symbol": Icons.euro_symbol,
  "event_seat": Icons.event_seat,
  "extension": Icons.extension,
  "favorite": Icons.favorite,
  "filter_alt": Icons.filter_alt,
  "fingerprint": Icons.fingerprint,
  "g_translate": Icons.g_translate,
  "gavel": Icons.gavel,
  "gif": Icons.gif,
  "grade": Icons.grade,
};
const Map<String, IconData> actionIcons = <String, IconData>{
  "home": Icons.home,
  "done": Icons.done,
  "shopping cart": Icons.shopping_cart,
  "visibility": Icons.visibility,
  "face": Icons.face,
  "description": Icons.description,
  "favorite border": Icons.favorite_border,
  "lock": Icons.lock,
  "thumb up": Icons.thumb_up,
  "verified": Icons.verified,
  "lightbulb": Icons.lightbulb,
  "question answer": Icons.question_answer,
  "verified user": Icons.verified_user,
  "print": Icons.print,
  "work": Icons.work,
  "pets": Icons.pets,
  "room": Icons.room,
  "explore": Icons.explore,
  "done all": Icons.done_all,
  "supervisor account": Icons.supervisor_account,
  "pending": Icons.pending,
  "view in Ar": Icons.view_in_ar,
  "pan tool": Icons.pan_tool,
  "flight takeoff": Icons.flight_takeoff,
  "get app": Icons.get_app,
  "label": Icons.label,
  "translate": Icons.translate,
  "loyalty": Icons.loyalty,
  "nightlight round": Icons.nightlight_round,
  "sensors": Icons.sensors,
  "copyright": Icons.copyright,
  "bookmarks": Icons.bookmarks,
  "invert colors": Icons.invert_colors,
  "important devices": Icons.important_devices,
  "theaters": Icons.theaters,
  "opacity": Icons.opacity,
  "tour": Icons.tour,
  "http": Icons.http,
  "wifi protected setup": Icons.wifi_protected_setup,
  "polymer": Icons.polymer
};

const Map<String, IconData> searchIcons = <String, IconData>{
  "chair": Icons.chair,
  "podcasts": Icons.podcasts,
  "shower": Icons.shower,
  "yard": Icons.coffee,
  "flatware": Icons.flatware,
  "coffee maker": Icons.coffee_maker,
  "blender": Icons.blender,
  "bedroom baby": Icons.bedroom_baby,
};

const Map<String, IconData> placesIcons = <String, IconData>{
  "storefront": Icons.storefront,
  "fitness center": Icons.fitness_center,
  "spa": Icons.spa,
  "ac unit": Icons.ac_unit,
  "checkroom": Icons.checkroom,
  "family restroom": Icons.family_restroom,
  "grass": Icons.grass,
  "all inclusive": Icons.all_inclusive,
  "airport shuttle": Icons.airport_shuttle,
  "child care": Icons.child_care,
  "beach access": Icons.beach_access,
  "pool": Icons.pool,
  "casino": Icons.casino,
  "roofing": Icons.roofing,
  "sports bar": Icons.sports_bar,
  "child friendly": Icons.child_friendly,
  "bathtub": Icons.bathtub,
  "golf course": Icons.golf_course,
  "stairs": Icons.stairs,
  "wash": Icons.wash,
  "smoking rooms": Icons.smoking_rooms,
  "fire extinguisher": Icons.fire_extinguisher,
  "charging station": Icons.charging_station,
  "carpenter": Icons.carpenter,
  "baby changing station": Icons.baby_changing_station,
  "umbrella": Icons.umbrella,
  "smoke free": Icons.smoke_free,
  "houseboat": Icons.houseboat,
  "iron": Icons.iron,
  "escalator": Icons.escalator,
};
